### ISSUE TITLE
hdr10+ issue

### ISSUE THREAD

**Issue by alikanarya** [xnappo/ez_dv_edid_fw#2]
Thanks for your work,
I couldnt get real hdr10+ signal from SP12H2.
My tv detects the test video as hdr10+ and displays the hdr10+ logo,
but test video plays as hdr10, not hdr10+.
I used the test video from https://ff.de/hdr10plus-metadata-test/.
It plays fine when I connect my media player to tv directly.
But if I use splitter, I got hdr10+ notification on tv but doesnt give 10+ effects.
Original firmware didnt work.
I used your v0.2\EZ-SP12H2_ML_10000_XNAPPODV, it is same as original.
Neither Edid copy nor 4k7 made any difference.
What is the problem you think for hdr10plus? Infact I had lost my hope with this device untill I came accross with your firmware.
Regards,

**Comment by xnappo** [comment]
Yes, the EZCOO FW does not include HDR10+.  Not sure what projector you have, but you can probably just use the HDR10+ versions that are in the LS12000 folder.

**Comment by alikanarya** [comment]
Thank you very much, I will give it a try.
