### ISSUE TITLE
Missing DD and DDP with Atmos support

### ISSUE THREAD

**Issue by mirobartovic** [xnappo/ez_dv_edid_fw#3]
Hi! My setup consists of LS11000 projector, Onkyo AVR with Atmos, CCwGTV, gaming PC and SP12H2. When I connect SP12H2 between projector and AVR the picture from my gaming PC drops out for some reason but that’s not the problem I want to solve here, just the reason why I want SP12H2 connected between Google TV and AVR. Unfortunately Google TV shows only DDP and DTS support at best in that configuration. DD and especially DDP with Atmos is shown as not supported. Without SP12H2 everything works. I tried pre-generated firmwares from “premade” and “LS12000” folders and also generating my own FW using the excel EDID calculator’s “EZCOO” and  “LS12000” tabs. AVR is connected to HDMI1 output of SP12H2 and EDID switch is in 4k7.1 position. Am I doing something wrong or the support for these codecs is just not there in the EDIDs?

**Comment by xnappo** [comment]
Hi - sorry for the delay - the EDIDs that you used were based upon just the projector EDID, which did not include full audio support.  I am pushing new versions into the LS12000 folder that are based off the original EZCOO FW instead.  Please give them a try.

**Comment by mirobartovic** [comment]
Thanks! I will try them when I have time and let you know how it went.
