### ISSUE TITLE
Will this work on SP12H21?

### ISSUE THREAD

**Issue by CasketPizza** [xnappo/ez_dv_edid_fw#6]
I cant find any info on what the difference is if any.

**Comment by xnappo** [comment]
See here:
https://www.avsforum.com/threads/alternative-devices-for-enabling-lldv-please-read-posts-1-2.3254266/page-189?post_id=63378134#post-63378134

and:
https://www.avsforum.com/threads/alternative-devices-for-enabling-lldv-please-read-posts-1-2.3254266/page-183?post_id=63219050#post-63219050
